/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Map;
import java.util.Vector;

/**
 *
 * @author admin
 */
public class TeacherPage extends javax.swing.JFrame {

    /**
     * Creates new form TeacherPage
     */
    public TeacherPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherLabel = new javax.swing.JLabel();
        assLabel = new javax.swing.JLabel();
        changePassword = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        assignmentScroll = new javax.swing.JScrollPane();
        assignmentTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teacherLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        teacherLabel.setText("Teacher Page");

        assLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        assLabel.setText("Select Assignment");

        changePassword.setText("Change Password");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        assignmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class", "Assignment Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        assignmentTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        assignmentScroll.setViewportView(assignmentTable);
        assignmentTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        updateTable();

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(teacherLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(assLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(changePassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(continueButton)
                                .addGap(54, 54, 54)
                                .addComponent(exitButton))
                            .addComponent(assignmentScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignmentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePassword)
                    .addComponent(continueButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        JPasswordField pf = new JPasswordField();
        int ok = JOptionPane.showConfirmDialog(rootPane, pf, "Enter new password!",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (ok != JOptionPane.OK_OPTION || pf.getText().equals(""))
            return;

        String pass = new String(pf.getPassword());
        SQLutils sql = new SQLutils(this);
        sql.update(String.format("update teachers set password = \'%s\' where teacherID = \'%s\';", Utils.encrypt(pass), TeacherLoginPage.loggedInTeacher.teacherID));
        sql.close();

        JOptionPane.showMessageDialog(this, "Password Changed!");
    }//GEN-LAST:event_changePasswordActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        int selectedRow = assignmentTable.getSelectedRow();
        ShowSolutionsPage.solutionAss = assignmentTable.getValueAt(selectedRow, 1).toString();
        new ShowSolutionsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_continueButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        Utils.exit(this, "Logging out!");
    }//GEN-LAST:event_exitButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        JPanel addAssignment = new JPanel();
        addAssignment.setLayout(new BoxLayout(addAssignment, BoxLayout.Y_AXIS));

        JTextField assNo = new HintTextField("Assignment Number");
        JTextField title = new HintTextField("Title");
        JTextField desc = new HintTextField("Description");
        JTextField lastdate = new HintTextField("Last Date");

        addAssignment.add(assNo);
        addAssignment.add(title);
        addAssignment.add(desc);
        addAssignment.add(lastdate);

        JOptionPane.showMessageDialog(rootPane, addAssignment, "Enter Assignment Details", JOptionPane.OK_CANCEL_OPTION);
        String numInput = assNo.getText();
        String titleInput = title.getText();
        String descInput = desc.getText();
        String dateInput = lastdate.getText();

        if (numInput.equals("") || titleInput.equals("") || descInput.equals("") || dateInput.equals("")) {
            Utils.showMessage(this, "Please enter proper details");
            return;
        }

        SQLutils sql = new SQLutils(this);
        sql.insert(new Assignment(TeacherLoginPage.loggedInTeacher.teacherID, TeacherLoginPage.loggedInTeacher.subID, numInput, titleInput, descInput, dateInput));
        sql.close();
    }//GEN-LAST:event_addButtonActionPerformed

    void updateTable() {
        DefaultTableModel table = (DefaultTableModel) assignmentTable.getModel();
        SQLutils sql = new SQLutils(this);
        List<Map<String, Object>> resultSet = sql.selectQueryWhere("t.tClass, a.assNo",
                "assignments a inner join teachers t on a.tchID = t.teacherID",
                String.format(" a.tchID=\'%s\'", TeacherLoginPage.loggedInTeacher.teacherID), "");
        sql.close();
        for (Map row : resultSet) {
            table.addRow(new Vector<>(row.values()));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel assLabel;
    private javax.swing.JTable assignmentTable;
    private javax.swing.JButton changePassword;
    private javax.swing.JButton continueButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane assignmentScroll;
    private javax.swing.JLabel teacherLabel;
    // End of variables declaration//GEN-END:variables
}
